package com.currentguardian.model

enum class GuardianEventType {

    GUARDIAN_STARTED,

    APP_DETECTED,
    APP_FOREGROUND,
    APP_BACKGROUND,
    APP_RETURNED_FOREGROUND,

    APP_CHANGED,
    APP_DISAPPEARED,

    USER_MARK,

    SCREEN_CHANGE,
    LOADING_STARTED,
    LOADING_FINISHED,

    NETWORK_CHANGED,
    NETWORK_DEGRADED,
    NETWORK_RECOVERED,

    RESOURCE_WARNING,
    RESOURCE_CRITICAL,

    RISK_CHANGED,

    CRITICAL_SNAPSHOT_CREATED,

    NORMAL_EXIT_SUSPECTED,
    ABNORMAL_EXIT_SUSPECTED,

    GUARDIAN_BACKGROUND,
    GUARDIAN_DESTROYED
}
